In [19]:
import pyvisa
import serial
from pyvisa.constants import StopBits, Parity

In [20]:
rm = pyvisa.ResourceManager()
print(rm.list_resources())
inst=rm.open_resource('GPIB1::20::INSTR')

('TCPIP0::172.031.105.214::HMP4040::INSTR', 'TCPIP0::172.31.105.237::hislip0::INSTR', 'TCPIP0::172.31.105.237::inst0::INSTR', 'TCPIP0::192.168.1.81::hislip0::INSTR', 'TCPIP0::192.168.1.81::inst0::INSTR', 'ASRL1::INSTR', 'ASRL6::INSTR', 'ASRL7::INSTR', 'ASRL8::INSTR', 'ASRL9::INSTR', 'ASRL12::INSTR', 'GPIB0::9::INSTR', 'GPIB1::20::INSTR')


In [3]:
inst.query('*IDN?')

'Hewlett-Packard, ESG-2000B, GB38240140, B.03.86\n'

In [ ]:
freq_list = '50 MHz, 40MHz'
inst.write(':list:FREQ ' + freq_list)

In [ ]:
import numpy as np
import array

n_waves = 2
freq_matrix = np.zeros((n_waves, 3))

for i in range(n_waves):
    freq_matrix[i] = float(np.array((input(f'write {i} array')), dtype=float))

# wave = np.zeros((1, n_waves))
# for i in range(n_waves):
#     np.append(wave[i])



# str(np.arange(50e6, 52e6, 1e6))[1:-1].replace(' ', ', ')

In [ ]:
import numpy as np

n_waves = 2
freq_matrix = np.zeros((n_waves, 3))

for i in range(n_waves):
    user_input = input(f'Enter three space-separated values for wave {i + 1}: ')
    freq_matrix[i] = np.array(list(map(float, user_input.split())))

print("Frequency Matrix:")
print(freq_matrix)

vectors_matrix = np.zeros((1, n_waves), dtype=np.object)
for i in range(n_waves):
    vectors_matrix[0][i] = np.arange(freq_matrix[i][0], freq_matrix[i][1], freq_matrix[i][2])

vectors_matrix = vectors_matrix.ravel()

In [ ]:
str(vectors_matrix[0])

In [1]:
import numpy as np

n_waves = 2
freq_matrix = np.zeros((n_waves, 3))

for i in range(n_waves):
    user_input = input(f'Enter three space-separated values for wave {i + 1}: ')
    freq_matrix[i] = np.array(list(map(float, user_input.split())))

print("Frequency Matrix:")
print(freq_matrix)

vectors_matrix = np.zeros((1, n_waves), dtype=object)
for i in range(n_waves):
    vectors_matrix[0][i] = np.arange(freq_matrix[i][0], freq_matrix[i][1], freq_matrix[i][2])

vectors_matrix = vectors_matrix.ravel()

a = ''.join(map(str, vectors_matrix))

print("Consequent String of Numbers:")
b = a.replace('[', '').replace(']', '' )

print(b)


Frequency Matrix:
[[30. 32.  1.]
 [40. 42.  1.]]
Consequent String of Numbers:
30. 31.40. 41.


In [ ]:
a

In [ ]:
b = a.replace('[', '')
b


In [ ]:
c = b.replace(']', ' ')
c

In [ ]:
b.replace(']', 'c')
b

In [ ]:
np.zeros((1, n_waves))

In [ ]:
np.zeros((1, n_waves))

In [ ]:
np.append(np.arange(50e6, 52e6, 1e6),(np.arange(50e6, 52e6, 1e6)))

In [ ]:
inst.write(':list:FREQ ' + a)

In [22]:
inst.query(':LIST:FREQ?')

'+3.0000000000000E+07,+3.1000000000000E+07,+4.0000000000000E+07,+4.1000000000000E+07,+3.0000000000000E+07,+3.0000000000000E+07,+3.0000000000000E+07,+3.0000000000000E+07\n'

In [12]:
import numpy as np
np.arange(10 , 10, 0)

ZeroDivisionError: division by zero

In [24]:
import numpy as np
n_vector = 3
freq_matrix = np.zeros((n_vector, 3))

for i in range(n_vector):
    values = input(f'Enter three space-separated values for vector {i + 1} (np.arange styled): ')
    freq_matrix[i] = np.array(list(map(float, values.split())))

print(freq_matrix)

vectors_matrix = np.zeros((1, n_vector), dtype=object)
for i in range(n_vector):
    if freq_matrix[i][0] != freq_matrix[i][1]:
        vectors_matrix[0][i] = np.arange(freq_matrix[i][0], freq_matrix[i][1], freq_matrix[i][2])
    elif freq_matrix[i][0] == freq_matrix[i][1]:
        vectors_matrix[0][i] = np.array([freq_matrix[i][0]] * int(freq_matrix[i][2]))
        
vectors_matrix = vectors_matrix.ravel()

joined_string = ''.join(map(str, vectors_matrix))

joined_string = joined_string.replace('[', '').replace(' ', ',').replace(']', ',' ).replace('\n', '')
print(joined_string)



[[3.0e+07 3.0e+07 4.0e+00]
 [2.0e+07 2.2e+07 1.0e+06]
 [1.0e+07 1.2e+07 1.0e+06]]
30000000.,30000000.,30000000.,30000000.,20000000.,21000000.,10000000.,11000000.,


In [21]:
inst.write(':list:FREQ ' + joined_string)

93

In [32]:
[freq_matrix[0][0]] * 2

[30.0, 30.0]